version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Preparing for tests
  build:
    commands:
      - echo Running tests
      - python -m unittest discover -s tests
  post_build:
    commands:
      - echo Build completed
